# Lab Excercise #4, Part makefile
# Lab Section: 201-X02L
# Lab Instructor’s Name: Calin Anton
# CMPUT 201
# Instructor's Name: Calin Anton

CFLAGS = -Wall
CC = gcc

compile: lab4E1 lab4E2
lab4E1: lab4E1.c
	$(CC) $(CFLAGS) lab4E1.c -o lab4E1
lab4E2: lab4E2.c
	$(CC) $(CFLAGS) lab4E2.c -o lab4E2
