# Student's Name: Patricia Zapansa
# Lab Excercise #6 makefile
# Lab Section: 201-X02L
# Lab Instructor’s Name: Calin Anton
# CMPUT 201
# Instructor's Name: Calin Anton

tar:
	tar -zcvf lab6.tar.gz lab6