compile: selectline.c
	gcc selectline.c -o selectline
testing:
	./selectline < selectlineInput1 > selectlineOutput1
	./selectline < selectlineInput2 > selectlineOutput2
	./selectline < selectlineInput3 > selectlineOutput3
	./selectline < selectlineInput4 > selectlineOutput4
